### ISSUE TITLE
macos 10.12 无效果

### ISSUE THREAD

**Issue by niu541412** [peterwang1996/QianFangGaoNeng#3]
mac chrome 53.0.2785.143 (64-bit)
商店插件版，装了之后页面无变化，已经打开开关
bilibili 用的是html5播放器

**Comment by peterwang1996** [comment]
请问 Mac 上是自动切换到 HTML5 播放器吗？
目前基本支持了 Flash 播放器，HTML5 播放器的接口我们还在探索。
感谢反馈。

**Comment by niu541412** [comment]
我后来在帮助中心里，关闭了html5。播放处就变成了新版和旧版两种flash。但是似乎还是没效果。

**Comment by peterwang1996** [comment]
我更新了一个版本，现在应该能基本完美适配官方H5播放器了，只是番剧页面还在适配中。

**Comment by niu541412** [comment]
感谢开发者～😊

**Comment by peterwang1996** [comment]
Problem solved, closing issue...
