### ISSUE TITLE
echarts和weui旧版本兼容性问题

### ISSUE THREAD

**Issue by niu541412** [peterwang1996/QianFangGaoNeng#4]
我试了试移植firefox
除去图标和设置界面等美观性问题。
echarts代码在firefox下存在兼容性bug，无法加载出图表。
较新的echarts版本已经修复此bug。

"'requestAnimationFrame' called on an object that does not implement interface Window."
可以参看https://github.com/ecomfe/zrender/issues/189#issuecomment-224919809

修改后可以正常使用。
不过似乎加载过程要比chrome慢得多，不知缘故。

希望您可以更新下代码，发布下firefox的版本。

**Comment by niu541412** [comment]
这两天又试了下Firefox Quantum，载入缓慢的问题没有了。看来是浏览器本身的问题。

此外您用的weui版本较低，开关按钮的ui对于非chrome也存在兼容性问题。较新版本weui的api里有个兼容开关。
参看https://github.com/Tencent/weui/issues/389#issuecomment-268747297


其实我觉得这个开关目前并没有什么大作用。不想用此功能的人直接禁用插件就行了。

**Comment by peterwang1996** [comment]
谢谢提醒～移植到其他浏览器和添加一些功能的确在我目前的计划中，但因为本人目前是考研狗，所以插件的更新会搁置一段时间。如果你有好的方案，或者制作了比较成熟的移植，欢迎你来pr，我会尽量抽时间来review和merge。再次感谢你对这个插件的持续关注～
