### ISSUE TITLE
发现一个番组网址匹配的问题。

### ISSUE THREAD

**Issue by niu541412** [peterwang1996/QianFangGaoNeng#6]
动画同样的一集，有两种番剧网址，比如
https://bangumi.bilibili.com/anime/5707/play#118543
https://www.bilibili.com/bangumi/play/ep118543
目前代码里只match了前一种。

你用的addEventListener('hashchange', ……) 
后者的url是pathname变了，判定条件需要改一下。
其实我不知道该用什么方法，似乎没有类似pathnamechange的事件类型。

还有前者的iframe的序号是1，后者是2。
不过你似乎用jQuery这点也不用考虑。

另外B站小部分重要电影还有个网址
比如http://bangumi.bilibili.com/movie/11936

**Comment by peterwang1996** [comment]
这一版大抵是不会管这个问题了，等2.0罢
________________________________
发件人: Shu Niu <notifications@github.com>
发送时间: 2017年12月27日 8:15:25
收件人: peterwang1996/QianFangGaoNeng
抄送: Subscribed
主题: [peterwang1996/QianFangGaoNeng] 发现一个番组网址匹配的问题。 (#6)


动画同样的一集，有两种番剧网址，比如
https://bangumi.bilibili.com/anime/5707/play#118543
https://www.bilibili.com/bangumi/play/ep118543
目前代码里只match了前一种。

前者的iframe的序号是1，后者是2，其他的都不用改动。

―
